task_id:"cgxnSbG7SuIkkt1vEeHd4" situation_id:"xiqOoFVZ199r1EazgQxr8" check_item:{check_item_id:"HhSVfkKPQptsUjo89wOH3" command:{command_id:"qk3vZpvy39xVZOvckpulT" command_line:"progate diagnose"} command:{command_id:"iIqA2S13bfOwGWcEo11vr" command_line:"bash ./.progate/check_puppeteer.sh"}} check_item:{check_item_id:"29JrxjopsEJpHjEk2ZAnP" command:{command_id:"JpEpioTfB747n4eWG35WA" command_line:"npm run lint:check"} command:{command_id:"0EAHmKPp1iXVlHeua8JMD" command_line:"npm run format:check"}} check_item:{check_item_id:"siXhhDH8zKoNjhcFCsA2V" command:{command_id:"0gDmAdX1b0Sbtw1OeV0Vc" command_line:"npm run test:expand_notation"}}